import type { NextApiRequest, NextApiResponse } from 'next'


var players = [
  {id: 1,
    nome: "Aegis",
    pos: "jg",
    time: "RED Canids",
    pontos: "",
    media_farm: "211",
    kda_total: "",
    kda_ultimo_game: "0/1/2",
    img_url: "https://i.imgur.com/KEMrpbB.png"},

  {id: 2,
    nome: "Avenger",
    pos: "mid",
    time: "RED Canids",
    pontos: "",
    media_farm: "",
    kda_total: "",
    kda_ultimo_game: "",
    img_url: "https://i.imgur.com/Vye5gp1.png"},

    {id: 3,
    nome: "Berserker",
    pos: "adc",
    time: "Cloud9",
    pontos: "",
    media_farm: "259",
    kda_total: "",
    kda_ultimo_game: "5/1/8",
    img_url: "https://i.imgur.com/dMyTdOb.png"},

    {id: 4,
    nome: "Blaber",
    pos: "jg",
    time: "Cloud9",
    pontos: "",
    media_farm: "153",
    kda_total: "",
    kda_ultimo_game: "2/1/11",
    img_url: "https://i.imgur.com/6yiqCln.png"},

    {id: 5,
    nome: "CarioK",
    pos: "jg",
    time: "paiN Gaming",
    pontos: "",
    media_farm: "184",
    kda_total: "",
    kda_ultimo_game: "2/3/10",
    img_url: "https://i.imgur.com/50KcCBf.png"},

    {id: 6,
    nome: "Damage",
    pos: "sup",
    time: "paiN Gaming",
    pontos: "",
    media_farm: "49",
    kda_total: "",
    kda_ultimo_game: "2/3/12",
    img_url: "https://i.imgur.com/5OJstZw.png"},

    {id: 7,
    nome: "Diplex",
    pos: "mid",
    time: "Cloud9",
    pontos: "",
    media_farm: "",
    kda_total: "",
    kda_ultimo_game: "",
    img_url: "https://i.imgur.com/I5VUbz9.png"},

    {id: 8,
    nome: "DudsTheBoy",
    pos: "adc",
    time: "KaBuM! e-Sports",
    pontos: "",
    media_farm: "217",
    kda_total: "",
    kda_ultimo_game: "6/2/9",
    img_url: "https://i.imgur.com/JQAAUp9.png"},

    {id: 9,
    nome: "dyNquedo",
    pos: "mid",
    time: "paiN Gaming",
    pontos: "",
    media_farm: "304",
    kda_total: "",
    kda_ultimo_game: "2/4/6",
    img_url: "https://i.imgur.com/Tw13WPF.png"},

    {id: 10,
    nome: "Faker",
    pos: "mid",
    time: "T1",
    pontos: "",
    media_farm: "263",
    kda_total: "",
    kda_ultimo_game: "2/5/6",
    img_url: "https://i.imgur.com/0ZCJ72w.png"},

    {id: 11,
    nome: "Fudge",
    pos: "top",
    time: "Cloud9",
    pontos: "",
    media_farm: "226",
    kda_total: "",
    kda_ultimo_game: "2/0/11",
    img_url: "https://i.imgur.com/9QNe4IC.png"},

    {id: 12,
    nome: "Guigo",
    pos: "top",
    time: "RED Canids",
    pontos: "",
    media_farm: "229",
    kda_total: "",
    kda_ultimo_game: "1/4/2",
    img_url: "https://i.imgur.com/QKq7nu3.png"},

    {id: 13,
    nome: "Gumayusi",
    pos: "adc",
    time: "T1",
    pontos: "",
    media_farm: "410",
    kda_total: "",
    kda_ultimo_game: "5/4/7",
    img_url: "https://i.imgur.com/8CdaoIV.png"},

    {id: 14,
    nome: "Hauz",
    pos: "mid",
    time: "KaBuM! e-Sports",
    pontos: "",
    media_farm: "206",
    kda_total: "",
    kda_ultimo_game: "7/2/10",
    img_url: "https://i.imgur.com/zzYh63Q.png"},

    {id: 15,
    nome: "Jojo",
    pos: "sup",
    time: "RED Canids",
    pontos: "",
    media_farm: "38",
    kda_total: "",
    kda_ultimo_game: "0/4/3",
    img_url: "https://i.imgur.com/1fS5ifq.png"},

    {id: 16,
    nome: "Keria",
    pos: "sup",
    time: "T1",
    pontos: "",
    media_farm: "24",
    kda_total: "",
    kda_ultimo_game: "3/1/11",
    img_url: "https://i.imgur.com/BPYCZ73.png"},

    {id: 17,
    nome: "Oner",
    pos: "jg",
    time: "T1",
    pontos: "",
    media_farm: "186",
    kda_total: "",
    kda_ultimo_game: "2/5/9",
    img_url: "https://i.imgur.com/VgE65YU.png"},

    {id: 18,
    nome: "Parang",
    pos: "top",
    time: "KaBuM! e-Sports",
    pontos: "",
    media_farm: "206",
    kda_total: "",
    kda_ultimo_game: "6/0/9",
    img_url: "https://i.imgur.com/r32DvIE.png"},

    {id: 19,
    nome: "Scuro",
    pos: "sup",
    time: "KaBuM! e-Sports",
    pontos: "",
    media_farm: "11",
    kda_total: "",
    kda_ultimo_game: "2/0/20",
    img_url: "https://i.imgur.com/Z8JKsOm.png"},

    {id: 20,
    nome: "TitaN",
    pos: "adc",
    time: "RED Canids",
    pontos: "",
    media_farm: "253",
    kda_total: "",
    kda_ultimo_game: "2/3/0",
    img_url: "https://i.imgur.com/LTQjysZ.png"},

    {id: 21,
    nome: "Trigo",
    pos: "adc",
    time: "paiN Gaming",
    pontos: "",
    media_farm: "317",
    kda_total: "",
    kda_ultimo_game: "9/5/6",
    img_url: "https://i.imgur.com/NUUBjJa.png"},

    {id: 22,
    nome: "Wiz",
    pos: "jg",
    time: "KaBuM! e-Sports",
    pontos: "",
    media_farm: "141",
    kda_total: "",
    kda_ultimo_game: "2/1/20",
    img_url: "https://i.imgur.com/gHmgJtE.png"},

    {id: 23,
    nome: "Wizer",
    pos: "top",
    time: "paiN Gaming",
    pontos: "",
    media_farm: "207",
    kda_total: "",
    kda_ultimo_game: "1/5/10",
    img_url: "https://i.imgur.com/ueTVrw6.png"},

    {id: 24,
    nome: "Zeus",
    pos: "top",
    time: "T1",
    pontos: "",
    media_farm: "288",
    kda_total: "",
    kda_ultimo_game: "2/5/6",
    img_url: "https://i.imgur.com/HaTacq6.png"},

    {id: 25,
    nome: "Zven",
    pos: "sup",
    time: "Cloud9",
    pontos: "",
    media_farm: "14",
    kda_total: "",
    kda_ultimo_game: "1/1/10",
    img_url: "https://i.imgur.com/BBdl560.png"}
]


export default function handler(req: NextApiRequest,res: NextApiResponse)
{
  return res.status(200).json(
    { status: 'true' }
    )
}
